robot_link_radius: 0.045
sample_state: [1,1,1,1,1,1]

boxes:
  - name: box1
    parameters: [1,1,1] # x, y, z
    coordinate_frame: 0
    rotation: [0,0,0]
    translation: [0,0,0]

  - name: box2
    parameters: [1,1,1]
    coordinate_frame: 6
    rotation: [0,0,0]
    translation: [0,0,0]

spheres:
  - name: sphere1
    parameters: 0.2 # r
    coordinate_frame: 0
    rotation: [1,0,0,0]
    translation: [0,0,0]

ellipsoids:
capsules:
cones:
cylinders:
  - name: cylinder1
    parameters: [0.1,3.0]
    coordinate_frame: 0
    rotation: [0,0,0]
    translation: [0,0,0]

  - name: cylinder2
    parameters: [0.1,1.0]
    coordinate_frame: 0
    rotation: [0,0,0]
    translation: [0,0,0]

meshes:
  - name: mesh1
    parameters:
      verts: [[1,1,1],[0,0,0],[2,2,2],[1,1,2]]
      tris: [[0,2,1],[0,3,2],[0,1,3],[1,2,3]]
    coordinate_frame: 0
    rotation: [0,0,0]
    translation: [0,0,0]
